{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "AddBlockPoolException.java",
  "functionName": "mergeException",
  "functionId": "mergeException___e-AddBlockPoolException",
  "sourceFilePath": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/AddBlockPoolException.java",
  "functionStartLine": 43,
  "functionEndLine": 55,
  "numCommitsSeen": 4,
  "timeTaken": 1406,
  "changeHistory": [
    "b0799148cf6e92be540f5665bb571418b916d789"
  ],
  "changeHistoryShort": {
    "b0799148cf6e92be540f5665bb571418b916d789": "Yintroduced"
  },
  "changeHistoryDetails": {
    "b0799148cf6e92be540f5665bb571418b916d789": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-14459. ClosedChannelException silently ignored in FsVolumeList.addBlockPool(). Contributed by Stephen O\u0027Donnell.\n\nSigned-off-by: Wei-Chiu Chuang \u003cweichiu@apache.org\u003e\n",
      "commitDate": "08/08/19 1:36 PM",
      "commitName": "b0799148cf6e92be540f5665bb571418b916d789",
      "commitAuthor": "Stephen O\u0027Donnell",
      "diff": "@@ -0,0 +1,13 @@\n+  public void mergeException(AddBlockPoolException e) {\n+    if (e \u003d\u003d null) {\n+      return;\n+    }\n+    for(FsVolumeSpi v : e.unhealthyDataDirs.keySet()) {\n+      // If there is already an exception for this volume, keep the original\n+      // exception and discard the new one. It is likely the first\n+      // exception caused the second or they were both due to the disk issue\n+      if (!unhealthyDataDirs.containsKey(v)) {\n+        unhealthyDataDirs.put(v, e.unhealthyDataDirs.get(v));\n+      }\n+    }\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  public void mergeException(AddBlockPoolException e) {\n    if (e \u003d\u003d null) {\n      return;\n    }\n    for(FsVolumeSpi v : e.unhealthyDataDirs.keySet()) {\n      // If there is already an exception for this volume, keep the original\n      // exception and discard the new one. It is likely the first\n      // exception caused the second or they were both due to the disk issue\n      if (!unhealthyDataDirs.containsKey(v)) {\n        unhealthyDataDirs.put(v, e.unhealthyDataDirs.get(v));\n      }\n    }\n  }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/AddBlockPoolException.java"
    }
  }
}