{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "CleanerTask.java",
  "functionName": "run",
  "functionId": "run",
  "sourceFilePath": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-sharedcachemanager/src/main/java/org/apache/hadoop/yarn/server/sharedcachemanager/CleanerTask.java",
  "functionStartLine": 109,
  "functionEndLine": 134,
  "numCommitsSeen": 2,
  "timeTaken": 648,
  "changeHistory": [
    "c51e53d7aad46059f52d4046a5fedfdfd3c37955"
  ],
  "changeHistoryShort": {
    "c51e53d7aad46059f52d4046a5fedfdfd3c37955": "Yintroduced"
  },
  "changeHistoryDetails": {
    "c51e53d7aad46059f52d4046a5fedfdfd3c37955": {
      "type": "Yintroduced",
      "commitMessage": "YARN-2183. [YARN-1492] Cleaner service for cache manager. (Chris Trezzo and Sangjin Lee via kasha)\n",
      "commitDate": "25/10/14 10:31 AM",
      "commitName": "c51e53d7aad46059f52d4046a5fedfdfd3c37955",
      "commitAuthor": "Karthik Kambatla",
      "diff": "@@ -0,0 +1,26 @@\n+  public void run() {\n+    if (!this.cleanerTaskLock.tryLock()) {\n+      // there is already another task running\n+      LOG.warn(\"A cleaner task is already running. \"\n+          + \"This scheduled cleaner task will do nothing.\");\n+      return;\n+    }\n+\n+    try {\n+      if (!fs.exists(root)) {\n+        LOG.error(\"The shared cache root \" + location + \" was not found. \"\n+            + \"The cleaner task will do nothing.\");\n+        return;\n+      }\n+\n+      // we\u0027re now ready to process the shared cache area\n+      process();\n+    } catch (Throwable e) {\n+      LOG.error(\"Unexpected exception while initializing the cleaner task. \"\n+          + \"This task will do nothing,\", e);\n+    } finally {\n+      // this is set to false regardless of if it is a scheduled or on-demand\n+      // task\n+      this.cleanerTaskLock.unlock();\n+    }\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  public void run() {\n    if (!this.cleanerTaskLock.tryLock()) {\n      // there is already another task running\n      LOG.warn(\"A cleaner task is already running. \"\n          + \"This scheduled cleaner task will do nothing.\");\n      return;\n    }\n\n    try {\n      if (!fs.exists(root)) {\n        LOG.error(\"The shared cache root \" + location + \" was not found. \"\n            + \"The cleaner task will do nothing.\");\n        return;\n      }\n\n      // we\u0027re now ready to process the shared cache area\n      process();\n    } catch (Throwable e) {\n      LOG.error(\"Unexpected exception while initializing the cleaner task. \"\n          + \"This task will do nothing,\", e);\n    } finally {\n      // this is set to false regardless of if it is a scheduled or on-demand\n      // task\n      this.cleanerTaskLock.unlock();\n    }\n  }",
      "path": "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-sharedcachemanager/src/main/java/org/apache/hadoop/yarn/server/sharedcachemanager/CleanerTask.java"
    }
  }
}