{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "AWSServiceIOException.java",
  "functionName": "isRetryable",
  "functionId": "isRetryable",
  "sourceFilePath": "hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/AWSServiceIOException.java",
  "functionStartLine": 68,
  "functionEndLine": 70,
  "numCommitsSeen": 1,
  "timeTaken": 661,
  "changeHistory": [
    "39ec1515a205952eda7e171408a8b83eceb4abde"
  ],
  "changeHistoryShort": {
    "39ec1515a205952eda7e171408a8b83eceb4abde": "Yintroduced"
  },
  "changeHistoryDetails": {
    "39ec1515a205952eda7e171408a8b83eceb4abde": {
      "type": "Yintroduced",
      "commitMessage": "HADOOP-13130. s3a failures can surface as RTEs, not IOEs. (Steve Loughran)\n",
      "commitDate": "21/05/16 8:39 AM",
      "commitName": "39ec1515a205952eda7e171408a8b83eceb4abde",
      "commitAuthor": "Steve Loughran",
      "diff": "@@ -0,0 +1,3 @@\n+  public boolean isRetryable() {\n+    return getCause().isRetryable();\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  public boolean isRetryable() {\n    return getCause().isRetryable();\n  }",
      "path": "hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/AWSServiceIOException.java"
    }
  }
}