{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "NativeAzureFileSystem.java",
  "functionName": "checkOpen",
  "functionId": "checkOpen",
  "sourceFilePath": "hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azure/NativeAzureFileSystem.java",
  "functionStartLine": 1210,
  "functionEndLine": 1214,
  "numCommitsSeen": 66,
  "timeTaken": 1225,
  "changeHistory": [
    "17aa8f6764262767b42717cf190a53e2c1795507"
  ],
  "changeHistoryShort": {
    "17aa8f6764262767b42717cf190a53e2c1795507": "Yintroduced"
  },
  "changeHistoryDetails": {
    "17aa8f6764262767b42717cf190a53e2c1795507": {
      "type": "Yintroduced",
      "commitMessage": "HADOOP-16785. Improve wasb and abfs resilience on double close() calls.\n\nThis hardens the wasb and abfs output streams\u0027 resilience to being invoked\nin/after close().\n\nwasb:\n  Explicity raise IOEs on operations invoked after close,\n  rather than implicitly raise NPEs.\n  This ensures that invocations which catch and swallow IOEs will perform as\n  expected.\n\nabfs:\n  When rethrowing an IOException in the close() call, explicitly wrap it\n  with a new instance of the same subclass.\n  This is needed to handle failures in try-with-resources clauses, where\n  any exception in closed() is added as a suppressed exception to the one\n  thrown in the try {} clause\n  *and you cannot attach the same exception to itself*\n\nContributed by Steve Loughran.\n\nChange-Id: Ic44b494ff5da332b47d6c198ceb67b965d34dd1b\n",
      "commitDate": "08/01/20 3:46 AM",
      "commitName": "17aa8f6764262767b42717cf190a53e2c1795507",
      "commitAuthor": "Steve Loughran",
      "diff": "@@ -0,0 +1,5 @@\n+    private void checkOpen() throws IOException {\n+      if (out \u003d\u003d null) {\n+        throw new IOException(FSExceptionMessages.STREAM_IS_CLOSED);\n+      }\n+    }\n\\ No newline at end of file\n",
      "actualSource": "    private void checkOpen() throws IOException {\n      if (out \u003d\u003d null) {\n        throw new IOException(FSExceptionMessages.STREAM_IS_CLOSED);\n      }\n    }",
      "path": "hadoop-tools/hadoop-azure/src/main/java/org/apache/hadoop/fs/azure/NativeAzureFileSystem.java"
    }
  }
}