{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "EditLogTailer.java",
  "functionName": "call",
  "functionId": "call",
  "sourceFilePath": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/EditLogTailer.java",
  "functionStartLine": 566,
  "functionEndLine": 583,
  "numCommitsSeen": 51,
  "timeTaken": 2757,
  "changeHistory": [
    "090272d7de7cb5f1133359d66780aef7c5cce5c9",
    "73615a789d96292e2731b5aa33ce46aa004d8211",
    "49dfad942970459297f72632ed8dfd353e0c86de"
  ],
  "changeHistoryShort": {
    "090272d7de7cb5f1133359d66780aef7c5cce5c9": "Ybodychange",
    "73615a789d96292e2731b5aa33ce46aa004d8211": "Ybodychange",
    "49dfad942970459297f72632ed8dfd353e0c86de": "Yintroduced"
  },
  "changeHistoryDetails": {
    "090272d7de7cb5f1133359d66780aef7c5cce5c9": {
      "type": "Ybodychange",
      "commitMessage": "HADOOP-15684. triggerActiveLogRoll stuck on dead name node, when ConnectTimeoutException happens. Contributed by Rong Tang.\n",
      "commitDate": "19/09/18 1:00 PM",
      "commitName": "090272d7de7cb5f1133359d66780aef7c5cce5c9",
      "commitAuthor": "Inigo Goiri",
      "commitDateOld": "06/09/18 2:48 PM",
      "commitNameOld": "eca1a4bfe952fc184fe90dde50bac9b0e5293568",
      "commitAuthorOld": "Giovanni Matteo Fumarola",
      "daysBetweenCommits": 12.93,
      "commitsBetweenForRepo": 166,
      "commitsBetweenForFile": 1,
      "diff": "@@ -1,24 +1,18 @@\n     public T call() throws IOException {\n       // reset the loop count on success\n       nnLoopCount \u003d 0;\n       while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n         try {\n           T ret \u003d doWork();\n           return ret;\n-        } catch (RemoteException e) {\n-          Throwable cause \u003d e.unwrapRemoteException(StandbyException.class);\n-          // if its not a standby exception, then we need to re-throw it, something bad has happened\n-          if (cause \u003d\u003d e) {\n-            throw e;\n-          } else {\n-            // it is a standby exception, so we try the other NN\n-            LOG.warn(\"Failed to reach remote node: \" + currentNN\n-                + \", retrying with remaining remote NNs\");\n-            cachedActiveProxy \u003d null;\n-            // this NN isn\u0027t responding to requests, try the next one\n-            nnLoopCount++;\n-          }\n+        } catch (IOException e) {\n+          LOG.warn(\"Exception from remote name node \" + currentNN\n+              + \", try next.\", e);\n+\n+          // Try next name node if exception happens.\n+          cachedActiveProxy \u003d null;\n+          nnLoopCount++;\n         }\n       }\n       throw new IOException(\"Cannot find any valid remote NN to service request!\");\n     }\n\\ No newline at end of file\n",
      "actualSource": "    public T call() throws IOException {\n      // reset the loop count on success\n      nnLoopCount \u003d 0;\n      while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n        try {\n          T ret \u003d doWork();\n          return ret;\n        } catch (IOException e) {\n          LOG.warn(\"Exception from remote name node \" + currentNN\n              + \", try next.\", e);\n\n          // Try next name node if exception happens.\n          cachedActiveProxy \u003d null;\n          nnLoopCount++;\n        }\n      }\n      throw new IOException(\"Cannot find any valid remote NN to service request!\");\n    }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/EditLogTailer.java",
      "extendedDetails": {}
    },
    "73615a789d96292e2731b5aa33ce46aa004d8211": {
      "type": "Ybodychange",
      "commitMessage": "HDFS-10536. Standby NN can not trigger log roll after EditLogTailer thread failed 3 times in EditLogTailer.triggerActiveLogRoll method (Contributed by XingFeng Shen\n",
      "commitDate": "26/06/16 3:15 AM",
      "commitName": "73615a789d96292e2731b5aa33ce46aa004d8211",
      "commitAuthor": "Vinayakumar B",
      "commitDateOld": "01/02/16 12:40 AM",
      "commitNameOld": "8f2622b6a0603f92e8b5784879da28d3d5797fc1",
      "commitAuthorOld": "Vinayakumar B",
      "daysBetweenCommits": 146.07,
      "commitsBetweenForRepo": 984,
      "commitsBetweenForFile": 1,
      "diff": "@@ -1,24 +1,24 @@\n     public T call() throws IOException {\n+      // reset the loop count on success\n+      nnLoopCount \u003d 0;\n       while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n         try {\n           T ret \u003d doWork();\n-          // reset the loop count on success\n-          nnLoopCount \u003d 0;\n           return ret;\n         } catch (RemoteException e) {\n           Throwable cause \u003d e.unwrapRemoteException(StandbyException.class);\n           // if its not a standby exception, then we need to re-throw it, something bad has happened\n           if (cause \u003d\u003d e) {\n             throw e;\n           } else {\n             // it is a standby exception, so we try the other NN\n             LOG.warn(\"Failed to reach remote node: \" + currentNN\n                 + \", retrying with remaining remote NNs\");\n             cachedActiveProxy \u003d null;\n             // this NN isn\u0027t responding to requests, try the next one\n             nnLoopCount++;\n           }\n         }\n       }\n       throw new IOException(\"Cannot find any valid remote NN to service request!\");\n     }\n\\ No newline at end of file\n",
      "actualSource": "    public T call() throws IOException {\n      // reset the loop count on success\n      nnLoopCount \u003d 0;\n      while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n        try {\n          T ret \u003d doWork();\n          return ret;\n        } catch (RemoteException e) {\n          Throwable cause \u003d e.unwrapRemoteException(StandbyException.class);\n          // if its not a standby exception, then we need to re-throw it, something bad has happened\n          if (cause \u003d\u003d e) {\n            throw e;\n          } else {\n            // it is a standby exception, so we try the other NN\n            LOG.warn(\"Failed to reach remote node: \" + currentNN\n                + \", retrying with remaining remote NNs\");\n            cachedActiveProxy \u003d null;\n            // this NN isn\u0027t responding to requests, try the next one\n            nnLoopCount++;\n          }\n        }\n      }\n      throw new IOException(\"Cannot find any valid remote NN to service request!\");\n    }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/EditLogTailer.java",
      "extendedDetails": {}
    },
    "49dfad942970459297f72632ed8dfd353e0c86de": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-6440. Support more than 2 NameNodes. Contributed by Jesse Yates.\n",
      "commitDate": "23/06/15 5:26 PM",
      "commitName": "49dfad942970459297f72632ed8dfd353e0c86de",
      "commitAuthor": "Aaron T. Myers",
      "diff": "@@ -0,0 +1,24 @@\n+    public T call() throws IOException {\n+      while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n+        try {\n+          T ret \u003d doWork();\n+          // reset the loop count on success\n+          nnLoopCount \u003d 0;\n+          return ret;\n+        } catch (RemoteException e) {\n+          Throwable cause \u003d e.unwrapRemoteException(StandbyException.class);\n+          // if its not a standby exception, then we need to re-throw it, something bad has happened\n+          if (cause \u003d\u003d e) {\n+            throw e;\n+          } else {\n+            // it is a standby exception, so we try the other NN\n+            LOG.warn(\"Failed to reach remote node: \" + currentNN\n+                + \", retrying with remaining remote NNs\");\n+            cachedActiveProxy \u003d null;\n+            // this NN isn\u0027t responding to requests, try the next one\n+            nnLoopCount++;\n+          }\n+        }\n+      }\n+      throw new IOException(\"Cannot find any valid remote NN to service request!\");\n+    }\n\\ No newline at end of file\n",
      "actualSource": "    public T call() throws IOException {\n      while ((cachedActiveProxy \u003d getActiveNodeProxy()) !\u003d null) {\n        try {\n          T ret \u003d doWork();\n          // reset the loop count on success\n          nnLoopCount \u003d 0;\n          return ret;\n        } catch (RemoteException e) {\n          Throwable cause \u003d e.unwrapRemoteException(StandbyException.class);\n          // if its not a standby exception, then we need to re-throw it, something bad has happened\n          if (cause \u003d\u003d e) {\n            throw e;\n          } else {\n            // it is a standby exception, so we try the other NN\n            LOG.warn(\"Failed to reach remote node: \" + currentNN\n                + \", retrying with remaining remote NNs\");\n            cachedActiveProxy \u003d null;\n            // this NN isn\u0027t responding to requests, try the next one\n            nnLoopCount++;\n          }\n        }\n      }\n      throw new IOException(\"Cannot find any valid remote NN to service request!\");\n    }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/ha/EditLogTailer.java"
    }
  }
}