{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "RetryPolicies.java",
  "functionName": "isSaslFailure",
  "functionId": "isSaslFailure___e-Exception",
  "sourceFilePath": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java",
  "functionStartLine": 744,
  "functionEndLine": 754,
  "numCommitsSeen": 30,
  "timeTaken": 802,
  "changeHistory": [
    "f2efaf013f7577948061abbb49c6d17c375e92cc"
  ],
  "changeHistoryShort": {
    "f2efaf013f7577948061abbb49c6d17c375e92cc": "Yintroduced"
  },
  "changeHistoryDetails": {
    "f2efaf013f7577948061abbb49c6d17c375e92cc": {
      "type": "Yintroduced",
      "commitMessage": "HADOOP-14982. Clients using FailoverOnNetworkExceptionRetry can go into a loop if they\u0027re used without authenticating with kerberos in HA env (pbacsko via rkanter)\n",
      "commitDate": "16/11/17 11:11 AM",
      "commitName": "f2efaf013f7577948061abbb49c6d17c375e92cc",
      "commitAuthor": "Robert Kanter",
      "diff": "@@ -0,0 +1,11 @@\n+  private static boolean isSaslFailure(Exception e) {\n+      Throwable current \u003d e;\n+      do {\n+          if (current instanceof SaslException) {\n+            return true;\n+          }\n+          current \u003d current.getCause();\n+      } while (current !\u003d null);\n+\n+      return false;\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private static boolean isSaslFailure(Exception e) {\n      Throwable current \u003d e;\n      do {\n          if (current instanceof SaslException) {\n            return true;\n          }\n          current \u003d current.getCause();\n      } while (current !\u003d null);\n\n      return false;\n  }",
      "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java"
    }
  }
}