{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "RetryPolicies.java",
  "functionName": "getWrappedRetriableException",
  "functionId": "getWrappedRetriableException___e-Exception",
  "sourceFilePath": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java",
  "functionStartLine": 756,
  "functionEndLine": 764,
  "numCommitsSeen": 30,
  "timeTaken": 1449,
  "changeHistory": [
    "3107434031e0da149ea2c09c5fc76f1a152435a0",
    "1fe1942328856dd832e9f94fb56a40ab3d810870"
  ],
  "changeHistoryShort": {
    "3107434031e0da149ea2c09c5fc76f1a152435a0": "Ymodifierchange",
    "1fe1942328856dd832e9f94fb56a40ab3d810870": "Yintroduced"
  },
  "changeHistoryDetails": {
    "3107434031e0da149ea2c09c5fc76f1a152435a0": {
      "type": "Ymodifierchange",
      "commitMessage": "HADOOP-12078. The default retry policy does not handle RetriableException correctly. (Contributed by Arpit Agarwal)\n",
      "commitDate": "09/06/15 8:58 PM",
      "commitName": "3107434031e0da149ea2c09c5fc76f1a152435a0",
      "commitAuthor": "Arpit Agarwal",
      "commitDateOld": "08/06/15 3:45 PM",
      "commitNameOld": "84ba1a75b6bcd696dfc20aeabb6f19cb4eff6011",
      "commitAuthorOld": "Arpit Agarwal",
      "daysBetweenCommits": 1.22,
      "commitsBetweenForRepo": 9,
      "commitsBetweenForFile": 1,
      "diff": "@@ -1,9 +1,9 @@\n-  private static RetriableException getWrappedRetriableException(Exception e) {\n+  static RetriableException getWrappedRetriableException(Exception e) {\n     if (!(e instanceof RemoteException)) {\n       return null;\n     }\n     Exception unwrapped \u003d ((RemoteException)e).unwrapRemoteException(\n         RetriableException.class);\n     return unwrapped instanceof RetriableException ? \n         (RetriableException) unwrapped : null;\n   }\n\\ No newline at end of file\n",
      "actualSource": "  static RetriableException getWrappedRetriableException(Exception e) {\n    if (!(e instanceof RemoteException)) {\n      return null;\n    }\n    Exception unwrapped \u003d ((RemoteException)e).unwrapRemoteException(\n        RetriableException.class);\n    return unwrapped instanceof RetriableException ? \n        (RetriableException) unwrapped : null;\n  }",
      "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java",
      "extendedDetails": {
        "oldValue": "[private, static]",
        "newValue": "[static]"
      }
    },
    "1fe1942328856dd832e9f94fb56a40ab3d810870": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-5291. Standby namenode after transition to active goes into safemode. Contributed by Jing Zhao.\n\ngit-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1530112 13f79535-47bb-0310-9956-ffa450edef68\n",
      "commitDate": "07/10/13 4:58 PM",
      "commitName": "1fe1942328856dd832e9f94fb56a40ab3d810870",
      "commitAuthor": "Jing Zhao",
      "diff": "@@ -0,0 +1,9 @@\n+  private static RetriableException getWrappedRetriableException(Exception e) {\n+    if (!(e instanceof RemoteException)) {\n+      return null;\n+    }\n+    Exception unwrapped \u003d ((RemoteException)e).unwrapRemoteException(\n+        RetriableException.class);\n+    return unwrapped instanceof RetriableException ? \n+        (RetriableException) unwrapped : null;\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  private static RetriableException getWrappedRetriableException(Exception e) {\n    if (!(e instanceof RemoteException)) {\n      return null;\n    }\n    Exception unwrapped \u003d ((RemoteException)e).unwrapRemoteException(\n        RetriableException.class);\n    return unwrapped instanceof RetriableException ? \n        (RetriableException) unwrapped : null;\n  }",
      "path": "hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/retry/RetryPolicies.java"
    }
  }
}