{
  "origin": "codeshovel",
  "repositoryName": "hadoop",
  "repositoryPath": "/home/shaiful/research/codeshovel/codeshovel-projects/hadoop/.git",
  "startCommitName": "HEAD",
  "sourceFileName": "FSNamesystem.java",
  "functionName": "unlockRetryCache",
  "functionId": "unlockRetryCache",
  "sourceFilePath": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java",
  "functionStartLine": 1049,
  "functionEndLine": 1053,
  "numCommitsSeen": 873,
  "timeTaken": 33265,
  "changeHistory": [
    "01ea6480564a9418230cd26b6f9dd54e28c51db0"
  ],
  "changeHistoryShort": {
    "01ea6480564a9418230cd26b6f9dd54e28c51db0": "Yintroduced"
  },
  "changeHistoryDetails": {
    "01ea6480564a9418230cd26b6f9dd54e28c51db0": {
      "type": "Yintroduced",
      "commitMessage": "HDFS-6229. Race condition in failover can cause RetryCache fail to work. Contributed by Jing Zhao.\n\ngit-svn-id: https://svn.apache.org/repos/asf/hadoop/common/trunk@1586714 13f79535-47bb-0310-9956-ffa450edef68\n",
      "commitDate": "11/04/14 9:42 AM",
      "commitName": "01ea6480564a9418230cd26b6f9dd54e28c51db0",
      "commitAuthor": "Jing Zhao",
      "diff": "@@ -0,0 +1,5 @@\n+  void unlockRetryCache() {\n+    if (retryCache !\u003d null) {\n+      retryCache.unlock();\n+    }\n+  }\n\\ No newline at end of file\n",
      "actualSource": "  void unlockRetryCache() {\n    if (retryCache !\u003d null) {\n      retryCache.unlock();\n    }\n  }",
      "path": "hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java"
    }
  }
}